### ISSUE TITLE
Add optional logging to file for exports

### ISSUE THREAD

**Issue by dimitri-koenig** [actualys/DrupalCommerceConnectorBundle#13]
For debug purposes, even in production mode, it should be possible to log every export.

I propose the following options per batch job, which should be included in the batch_jobs.yml file:

```
logging:
    active: true # default should be false to maintain backwards compatibility
    log_path: logs/export/
    log_rotate: true # create daily logs
```
